config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :invoices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  validates :company_name, :price, :paid_with, presence: true

  belongs_to :user

  CATEGORIES = ['Amber Bakery', 'RoExport', 'Monolith', 'Lithuanian Beer', 'Asorti Food', 'Marion', 'Cake World', 'Cypro Food',
                 'Imperial', 'Sitella Fruits', 'Ambassador Bakery', 'Dancle Romanian', 'Noble Wine', 'Baltic Foods', 'Ulan',
                'Lackmann', 'Leon', 'Bills', 'Holland Bazar', 'Tahtakale', 'Rambynas', 'Salary', 'Import', 'Other',
                'Foods 444', 'Lithuanica', 'Fuel', 'Eggs UK', 'Polsih Bread', 'Modlova Foods', 'Romanian Drink', 'Ciggaretes', 'Solo Bars',
                'Fish', 'Oyster' ].sort
  PAID = ["Card", "Cash"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :invoices

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def index
    if params[:sort] == "current"
      @invoices = Invoice.where("created_at >= ?", DateTime.now.beginning_of_week)
    elsif params[:sort] == "last_week"
      @invoices = Invoice.where("created_at >= ? and created_at <= ?", DateTime.now.beginning_of_week - 7, DateTime.now.end_of_week - 7)
    elsif params[:sort] == "current_month"
      @invoices =  Invoice.where("created_at >= ? and created_at <= ?", DateTime.now.beginning_of_month, DateTime.now.end_of_month)
    elsif params[:sort] == "last_month"
      @invoices =  Invoice.where("created_at >= ? and created_at <= ?", DateTime.now.beginning_of_month.prev_month , DateTime.now.end_of_month.prev_month )
    elsif params[:sort] == "newest"
      @invoices = Invoice.order(created_at: :desc)
    else
      @invoices = Invoice.all
    end

    if params[:q].present?
      @invoices = Invoice.where("company_name ILIKE ?", "%#{params[:q]}%")
    else
      @invcoices = Invoice.all
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
    # @user = User.find(@user_id)
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.user = current_user
    if @invoice.save
      redirect_to invoices_path(@invoice)
    else
      render :new, stauts: :unprocessable_entity
    end
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

  def update
    @invoice = Invoice.find(params[:id])
    @invoice.update(invoice_params)
    redirect_to invoice_path(@invoice)
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    redirect_to invoices_path, notice: 'Post was successfully deleted.', status: :see_other
  end

  private

  def invoice_params
    params.require(:invoice).permit(:company_name, :invoice_number, :price, :paid_with)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def inv
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoices/edit.html.erb
<div class = "banner-new">
  <div class="create">
    <h1>Edit an Invoice</h1>
  </div>
  <div class="container">
    <%= simple_form_for @invoice do |f| %>
      <%= f.input :company_name, collection: Invoice::CATEGORIES %>
      <%= f.input :invoice_number %>
      <%= f.input :price %>
      <%= f.input :paid_with, collection: Invoice::PAID %>
      <%= f.submit "Edit Invoice", class: 'btn btn-primary text-white' %>
      <%= link_to "Back to Main page", invoices_path, class: 'btn btn-danger text-white', style: 'margin: 10px;'  %>
    <% end %>
  </div>
</div>

app/views/invoices/index.html.erb
<div class="wrapper" style="width: 100vw;
                           text-align: center;
                           margin-top: 50px;">
  <% if user_signed_in? %>
    <h1>Invoices for <%= current_user.email %></h1>

    <div class="buttons">
      <%= link_to "Create New", new_invoice_path,  class: 'btn btn-primary text-white' %>
      <%= link_to "See All Invoices", invoices_path, class: 'btn btn-success text-white' %>
    </div>

    <div class="filters">
        <form action = "/invoices" class="forms">
      Time: <select aria-labelledby="refine-sortlabel" name="sort" data-q="srp-sort">
          <option value="current">Current Week</option>
          <option value="last_week">Last Week</option>
          <option value="current_month">Current Month</option>
          <option value="last_month">Last Month</option>
          <option value="newest">Newest</option>
          <option value="oldest">Oldest to Newest</option>
        </select>
        <input type="submit" value="Submit" id="submit">
        </form>



        <form action = "/invoices" class="forms">
        Companies:  <select aria-labelledby="refine-sortlabel" name="q" data-q="srp-sort">
          <option value="Amber">Amber Bakery</option>
          <option value="RoExport">RoExport</option>
          <option value="Monolith">Monolith</option>
          <option value="Lithuanian_Beer">Lithuanian Beer</option>
          <option value="Asorti_Foods">Asorti Foods</option>
          <option value="Marion">Marion</option>
          <option value="Cake_World">Cake World</option>
          <option value="Cypro">Cypro Foods</option>
          <option value="Imperial">Imperial</option>
          <option value="Sitella">Sitella Fruits</option>
          <option value="Ambassador">Ambassador Bakery</option>
          <option value="Dancle">Dancle Romanian</option>
          <option value="Noble">Noble Wine</option>
          <option value="Baltic">Baltic Foods</option>
          <option value="Ulan">Ulan</option>
          <option value="Lackamnn">Lackmann</option>
          <option value="Leon">Leon</option>
          <option value="Bills">Bills</option>
          <option value="Holland">Holland Bazar</option>
          <option value="Tahtakale">Tahtakale</option>
          <option value="Rambynas">Rambynas</option>
          <option value="Salary">Salary</option>
          <option value="Import">Import</option>
          <option value="Other">Other</option>
          <option value="Lithuanica">Lithuanica</option>
          <option value="444">Foods 444</option>
          <option value="Fuel">Fuel</option>
          <option value="Eggs">Eggs UK</option>
          <option value="Polsih">Polish Bread</option>
          <option value="Moldova">Moldova Foods</option>
          <option value="Romanian_Drink">Romanian Drink</option>
          <option value="Ciggaretes">Cigarettes</option>
          <option value="Solo">Solo Bars</option>
          <option value="Fish">Fish</option>
           <option value="Oyster">Oyster</option>
        </select>
        <input type="submit" value="Submit" id="submit">
        </form>
    </div>
    <div class="table">
      <table class="wp-table">
        <tr>
          <th>Created At</th>
          <th>Company</th>
          <th>Number</th>
          <th>Price</th>
          <th>Card/Cash</th>
        <tr>

          <% @invoices.each do |invoice| %>
             <% if current_user.id == invoice.user_id %>
            </tr>
              <td><%= invoice.created_at.to_date %></td>
              <td class="company_name"><%= link_to invoice.company_name, invoice_path(invoice), class: "name" %></td>
              <td><%= invoice.invoice_number.upcase %></td>
              <td><%=  invoice.price  %></td>
              <td><%= invoice.paid_with %></td>
            </tr>
            <% end %>
          <% end %>

        <tfoot>
          <tr>
              <% sumcard = 0 %>
                <%# <strong><td class="sum" colspan="2">You have <%= @invoices.length invoices</td></strong> %>
              <% @invoices.each do |invoice| %>
                <% if current_user.id == invoice.user_id %>
                  <% if invoice.paid_with === 'card' || invoice.paid_with === 'Card' %>
                  <% sumcard += invoice.price.to_f %>
                  <% end %>
                <% end %>
            <% end %>
            <td class="sum" colspan="2">£<%= sumcard.round(2) %> total card</td>

              <% sumcash = 0 %>
              <% @invoices.each do |invoice| %>
                <% if current_user.id == invoice.user_id %>
                  <% if invoice.paid_with === 'cash' || invoice.paid_with === 'Cash' %>
                  <% sumcash += invoice.price.to_f %>
                  <% end %>
                <% end %>
              <% end %>
            <td class="sum">£<%= sumcash.round(2) %> total cash</td>

             <% sum = 0 %>
              <% @invoices.each do |invoice| %>
                <% if current_user.id == invoice.user_id %>
                  <% sum += invoice.price.to_f %>
                <% end %>
              <% end %>
                <td class="sum" colspan="2">£<%= sum.round(2) %> total</td>

            </tr>
        </tfoot>
      </table> <%# end of table div %>
    </div>
  <% else %>
    <h1>Invoicing System</h1>
    <h3>Invoicing System Require LogIn To start Invoicing</h3>
    <%= link_to "Please Sign in", user_session_path, class: 'btn btn-lg btn-primary text-white' %>

  <% end %>
</div>

app/views/invoices/new.html.erb
<div class = "banner-new">
  <div class="create">
    <h1>Add an Invoice</h1>
  </div>
  <div class="container">
    <%= simple_form_for @invoice do |f| %>
      <%= f.input :company_name, collection: Invoice::CATEGORIES %>
      <%= f.input :invoice_number %>
      <%= f.input :price %>
      <%= f.input :paid_with, collection: Invoice::PAID %>
      <%= f.submit "Add Invoice", class: 'btn btn-primary text-white' %>
      <%= link_to "Back to Main page", invoices_path, class: 'btn btn-danger text-white', style: 'margin: 10px;'  %>
    <% end %>
  </div>
</div>

app/views/invoices/show.html.erb
<div class="wrapper-show">
  <div class="show-header">
    <h1>Company name: <%= @invoice.company_name %></h1>
    <h3>Invoice ready to Edited or Deleted.</h3>
  </div>
  <div class="show-body">
    <p>Invoice Number: <%= @invoice.invoice_number %></p>
    <p>Invoice Price: <%= @invoice.price %></p>
    <p>Paid in: <%= @invoice.paid_with %></p>
    <%= link_to "Edit", edit_invoice_path,  class: "btn btn-success text-white" %>
    <%= link_to "Delete", invoice_path(@invoice), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },  class: "btn btn-danger text-white" %>
    <%= link_to 'Main Page', invoices_path, class: "btn btn-primary text-white" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceSorting</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper-home" style="text-align: center">
  <div class="home-body">
      <h1>Invoicing System</h1>

  <%= link_to 'See All Invoices', invoices_path, class: "btn btn-success text-white" %>

    <p>A small app where you can keep track of all your invoices.</p>
    <p>Suitable for small businesses.</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img id="logo" src="https://images.unsplash.com/photo-1654263937100-df57fa2be69d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGludm9pY2V8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
          <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path,  data: {turbo_method: :delete}, class: "nav-link"  %>
            <%# <a class="nav-link", destroy_user_session_path, data-turbo-method="delete", href="#">Log out</a> %>
          </li>
          <% else %>
            <%= link_to "Login/Register", new_user_session_path, class: "nav-link" %>
          <% end %>
      </ul>
    </div>
  </div>
</div>